# Generated by Django 4.1.1 on 2022-10-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_noticias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='Fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
